@startuml
title Add Command - Sequence Diagram

participant ":AddCommand" as AC
participant ":Internship" as IN
participant "<<class>>\nInternshipList" as IL
participant "List<Internship>" as LI
participant ":Ui" as Ui

activate AC

== Create a new Internship object ==
AC -> IN: Internship()
activate IN
IN --> AC
deactivate IN

== Add to InternshipList ==
AC -> IL: add()
activate IL
IL -> LI: add()
activate LI
LI --> IL
IL --> AC
deactivate LI
deactivate IL

== Display Confirmation ==
AC -> Ui: printAddInternship()
activate Ui
Ui --> AC
deactivate Ui

deactivate AC

@enduml