@startuml
title Add Command - Sequence Diagram
participant Logic
create ":AddCommand" as AC
participant ":Internship" as IN
participant "<<class>>\nInternshipList" as IL
participant "List:ArrayList<Internship>" as LI
participant ":Ui" as Ui

Logic-> AC**: new AddCommand(...)
activate AC
return (created)

Logic-> AC: execute()
activate AC

AC -> IN: Internship(...)
activate IN
IN --> AC
deactivate IN

AC -> IL: add(...)
activate IL
IL -> LI: add()
activate LI
LI --> IL
deactivate LI
IL --> AC
deactivate IL



AC -> Ui: print added internship
activate Ui
Ui --> AC
deactivate Ui

AC -->Logic
deactivate AC
@enduml