@startuml ModelComponentSD
!include Style.puml
title List Command - Sequence Diagram

'abstracted Logic components
participant "Logic" as Logic
participant "command : ListCommand" as Command

' Model components
participant "<<class>>\nInternshipList" as Model
participant "internship : Internship" as internship

' Ui component
participant "<<class>>\nUi" as Ui

' creation of ListCommand
create Command
Logic -> Command : new ListCommand(OrderType)
activate Command
Command --> Logic : (created)
deactivate Command

' execution of ListCommand
Logic -> Command : execute()
activate Command
Command -> Model : listAll()
activate Model
Model -> Model : check if list is empty
activate Model
Model --> Model : return boolean
deactivate Model
alt list is empty
    Model -> Ui : printInternshipListEmpty()
    activate Ui
    Ui -> Ui : print empty list message
    activate Ui
    Ui --> Ui
    deactivate Ui
    Ui --> Model
    deactivate Ui
    Model --> Command
    Command --> Logic
else list is not empty
    Model -> Model : sortInternships(OrderType)
    activate Model
    Model --> Model
    deactivate Model
    Model -> Ui : printInternshipListHeader(messsage)
    activate Ui
    Ui -> Ui : print header message
    activate Ui
    Ui --> Ui
    deactivate Ui
    Ui --> Model
    deactivate Ui
    loop for each internship in List

        Model -> Ui : printInternshipListContent(internship)
        activate Ui
        Ui -> internship : get internship details
        activate internship
        internship --> Ui : return details
        deactivate internship
        Ui -> Ui : print internship details
        activate Ui
        Ui --> Ui
        deactivate Ui
        Ui --> Model
        deactivate Ui
    end
    Model --> Command
    deactivate Model
    Command --> Logic
    deactivate Command
end

@enduml