@startuml ModelComponentSD
title List Feature - Sequence Diagram

box Logic #FFFFFF
participant ":InternityManager" as Manager
participant ":CommandParser" as Parser
participant "command : ListCommand" as Command
end box

box Model #F0F0F0
participant "internship : Internship" as internship
participant "<<class>> InternshipList" as Model
end box

Parser -> Manager : create List Command
activate Command
Manager -> Command : execute()

Model -> Model : check if list is empty
alt list is empty
    Model -> Model : print "List is empty" message
    Model --> Command
    Command --> Manager
else list is not empty
    Model -> Model : sortInternships(orderType)
    Model -> Model : print internship list table header
    loop for each internship in List
        Model -> internship : get internship details
        internship --> Model : return details
        Model -> Model : format and print internship details
    end
    Model --> Command
    Command --> Manager
end

@enduml