@startuml ModelComponentSD
!include Style.puml
title List Command - Sequence Diagram

'abstracted Logic components
participant "Logic" as Logic
participant "command : ListCommand" as Command

' Model components
participant "<<class>>\nInternshipList" as Model
participant "internship : Internship" as internship

' Ui component
participant "<<class>>\nUi" as Ui

' creation of ListCommand
create Command
Logic -> Command : new ListCommand(OrderType)
activate Command
Command --> Logic : (created)
deactivate Command

' execution of ListCommand
Logic -> Command : execute()
activate Command
Model -> Model : check if list is empty
alt list is empty
    Model -> Ui : printInternshipListEmpty()
    Ui -> Ui : print empty list message
    Ui --> Model
    Model --> Command
    Command --> Logic
else list is not empty
    Model -> Model : sortInternships(OrderType)
    Model -> Ui : printInternshipListHeader(messsage)
    Ui -> Ui : print header message
    Ui --> Model
    loop for each internship in List

        Model -> Ui : printInternshipListContent(internship)
        Ui -> internship : get internship details
        internship --> Ui : return details
        Ui -> Ui : print internship details
        Ui --> Model
    end
    Model --> Command
    Command --> Logic
    deactivate Command
end

@enduml