@startuml ModelComponentSD
title Model Component - Sequence Diagram

box Logic #FFFFFF
participant "command : AddCommand" as Command
end box
box Model
participant "internship : Internship" as internship
participant "<<class>> InternshipList" as Model
end box

box Ui #FFFFFF
participant "<<class>> Ui" as Ui
end box

activate Command
-> Command : execute()

Command -> internship : new Internship(company, role, deadline, pay)
activate internship
internship --> Command : Internship
Command -> Model : add(internship)
Model -> Model : add internship to List
Model --> Command
Command -> Ui : printAddSuccess(internship)
deactivate internship



<-- Command
destroy internship

deactivate Command
destroy Command

@enduml