@startuml
title UI Component Diagram

actor User

rectangle "Logic" {
    [Command]
}

rectangle "Core" {
    [InternshipList]
}

rectangle "UI" {
    [Ui]
    [DashboardUi]
}

User --> [Ui] : inputs & views output
[InternityManager] --> [Ui] : call display methods
[Command] --> [Ui] : print messages
[Command] --> [DashboardUi] : show dashboard
[DashboardUi] --> [InternshipList] : fetch data

@enduml
